# Generated by Django 3.0.5 on 2020-04-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='EquipmentFinancing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'equipment_financing',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='InvoiceFactoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoice_factoring',
            },
        ),
        migrations.CreateModel(
            name='InvoiceFinancing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoice_financing',
            },
        ),
        migrations.CreateModel(
            name='LinesOfCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lines_of_credit',
            },
        ),
        migrations.CreateModel(
            name='SbaLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sba_loan',
            },
        ),
        migrations.CreateModel(
            name='ShortTermLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'short_term_loan',
            },
        ),
        migrations.CreateModel(
            name='TermLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=15)),
                ('term_length', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'term_loan',
            },
        ),
        migrations.CreateModel(
            name='WebsiteCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=50)),
                ('booking_on_page', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('chat_bot', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('pages_needed', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('about_you', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('domain_owned', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'website_creation',
            },
        ),
        migrations.CreateModel(
            name='TollFreeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll_free_number_needed', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'toll_free_number',
            },
        ),
        migrations.CreateModel(
            name='StoreCreditVendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('terms', models.CharField(max_length=50)),
                ('report_to', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
            ],
            options={
                'db_table': 'store_credit_vendor',
            },
        ),
        migrations.CreateModel(
            name='RevolvingCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('terms', models.CharField(max_length=50)),
                ('report_to', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
            ],
            options={
                'db_table': 'revolving_credit',
            },
        ),
        migrations.CreateModel(
            name='RevenueLending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fico_score', models.CharField(max_length=50)),
                ('equifax_score', models.CharField(max_length=50)),
                ('transunion_score', models.CharField(max_length=50)),
                ('avg_monthly_revenue', models.CharField(max_length=50)),
                ('abg_daily_balance', models.CharField(max_length=50)),
                ('avg_monthly_ending_balance', models.CharField(max_length=50)),
                ('business_debt', models.CharField(max_length=50)),
                ('liens', models.CharField(max_length=50)),
                ('business_bank_account', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('registerd_at', models.DateTimeField()),
                ('lender_name', models.CharField(max_length=50)),
                ('personal_credit_score', models.CharField(max_length=50)),
                ('time_in_business', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=50)),
                ('term_length', models.CharField(max_length=50)),
                ('apr', models.CharField(max_length=50)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'revenue_lending',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_number', models.CharField(max_length=50)),
                ('website_creation', models.CharField(max_length=50)),
                ('virtual_number', models.CharField(max_length=50)),
                ('fax_number', models.CharField(max_length=50)),
                ('toll_free_number', models.CharField(max_length=50)),
                ('business_bank_account', models.CharField(max_length=50)),
                ('listing', models.CharField(max_length=50)),
                ('professional_email_address', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address_needed', models.CharField(max_length=50)),
                ('domain_present', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'professional_email_address',
            },
        ),
        migrations.CreateModel(
            name='Nopg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('report_to', models.CharField(max_length=50)),
                ('monthly_payment', models.CharField(max_length=15)),
                ('estimated_term', models.DateField()),
                ('payment_terms', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
            ],
            options={
                'db_table': 'nopg',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('report_to', models.CharField(max_length=50)),
                ('monthly_payment', models.CharField(max_length=15)),
                ('estimated_term', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
            ],
            options={
                'db_table': 'lender',
            },
        ),
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax_needed', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'fax',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('domain_needed', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'domain',
            },
        ),
    ]
