# Generated by Django 3.0.5 on 2020-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermloan',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shorttermloan',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
