# Generated by Django 3.0.5 on 2020-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200413_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermloan',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorttermloan',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
