# Generated by Django 3.0.5 on 2020-04-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200414_1045'),
        ('business', '0005_auto_20200414_1427'),
    ]

    operations = [
    ]
