# Generated by Django 3.0.5 on 2020-04-14 18:02

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20200414_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(max_length=50)),
                ('min_credit_score', models.CharField(max_length=50)),
                ('credit_bureau', models.CharField(max_length=50)),
                ('debt_ratio', models.CharField(max_length=50)),
                ('bankruptcy', models.CharField(max_length=50)),
                ('credit_data', models.CharField(max_length=50)),
                ('apr', models.CharField(max_length=50)),
                ('misc_info', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_credit_card',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(max_length=50)),
                ('min_credit_score', models.CharField(max_length=50)),
                ('credit_bureau', models.CharField(max_length=50)),
                ('debt_ratio', models.CharField(max_length=50)),
                ('bankruptcy', models.CharField(max_length=50)),
                ('credit_data', models.CharField(max_length=50)),
                ('apr', models.CharField(max_length=50)),
                ('misc_info', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_credit_card',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('terms', models.CharField(max_length=50)),
                ('inquiries', models.CharField(max_length=50)),
                ('credit_bureau', models.CharField(max_length=50)),
                ('states', models.CharField(max_length=50)),
                ('credit_score', models.CharField(max_length=50)),
                ('emp_length', models.CharField(max_length=50)),
                ('credit_history', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personal_loan',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
    ]
