# Generated by Django 3.0.5 on 2020-04-16 14:21

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_nopg_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCreditTradeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50)),
                ('hard_check', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('strategy', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_credit_tradeline',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
    ]
